### ISSUE TITLE
Generate builds via Makefile

### ISSUE THREAD

**Issue by komish** [komish/unstaged#2]
Makefile is staged but needs to generate builds based on platform.

**Comment by dixonwille** [comment]
I am not sure what you are looking for here? Go already builds on what platform it is running on. Or do you want `make build` to build the top few OSs and stick them in a directory?

**Comment by dixonwille** [comment]
I don't think you need this if all you want to do is make releases and publish them (#3).

**Comment by komish** [comment]
> Or do you want `make build` to build the top few OSs and stick them in a directory?

This, exactly! Thanks for the help @dixonwille.

I'm mostly trying to automate cross-compile for each release here. So being able to `make build` to a `builds/` is the goal.

**Comment by komish** [comment]
Resolved my #13
