### ISSUE TITLE
Generate releases

### ISSUE THREAD

**Issue by komish** [komish/unstaged#3]
Need to build and publish release and tag. Blocked by #2.

**Comment by dixonwille** [comment]
I can do this without #2 I think. Mind if I take a shot?

**Comment by komish** [comment]
@dixonwille What did you have in mind? I'm not super familiar with the "Releases" functionality here in GH. At the very least I'd like to set up versioning to correspond with my tag (here means a top-level version.go file), but I haven't put much thought into this quite yet. 

Happy to hear what you're interested in doing, but I'm not sure what I'm ready to move forward with yet for this.

**Comment by dixonwille** [comment]
https://github.com/komish/unstaged/pull/11 Take a look at this. `goreleaser` is really nice for small projects and binaries. Hooks great into Travis CI as well. Once you setup Travis CI with this repo, all you have to do is tag this repository and let Travis CI and goreleaser do its magic.

https://goreleaser.com/

Feel free to let me know if you have questions, but this removes the need for Makefile. I personally not a fan of Makefiles in go projects unless you have complicated build steps (like generating files before build). Let me know what you think!

**Comment by komish** [comment]
Ah, I see! I'll definitely check it out soon.
