### ISSUE TITLE
Use XDG Base Directory standards

### ISSUE THREAD

**Issue by komish** [komish/unstaged#5]
For *nix systems, it may be better to default to checking in `${XDG_CONFIG_HOME}` for config files, but this adds some complexity and doesn't apply to Windows-based environments.

https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by tonyskapunk** [comment]
Yep, I was thinking the same, I'll do after #7 :)

**Comment by komish** [comment]
@tonyskapunk thanks! I think `os.UserConfigDir()` might be good for this. [Docs](https://golang.org/pkg/os/#UserConfigDir).
